name: simple
description: This is simple chat app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  japx: ^2.1.0
  json_serializable: ^6.7.1

dev_dependencies:
  analyzer: 5.13.0
  build_runner: 2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any


flutter:
  uses-material-design: true

  fonts:
    - family: LibreBarcode128
      fonts:
        - asset: assets/fonts/LibreBarcode128-Regular.ttf